version: '3.9'
services:
  database:
    image: postgres:16.2
    container_name: database
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abc12345
      POSTGRES_DB: testdb
    networks:
      - nestjs-networks
networks:
  nestjs-networks: